

#         Powered by TabooLib 6.0         #


name: AmazingBot
main: com.xbaimiao.easybot.EasyBot
version: ${project.version}
authors: [xbaimiao, jim20071128]

api-version: 1.13

lib-download: true
lib-version: 6.02-3
loader-version: 1.26
commands:
  amazingbot:
    aliases:
      - amb